DELETE FROM `wp_country_province` WHERE `code_country` = 'us';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('us', 'us-ak', 'Alaska'),
('us', 'us-al', 'Alabama'),
('us', 'us-ar', 'Arkansas'),
('us', 'us-az', 'Arizona'),
('us', 'us-ca', 'California'),
('us', 'us-co', 'Colorado'),
('us', 'us-ct', 'Connecticut'),
('us', 'us-dc', 'D.C.'),
('us', 'us-de', 'Delaware'),
('us', 'us-fl', 'Florida'),
('us', 'us-ga', 'Georgia'),
('us', 'us-hi', 'Hawaii'),
('us', 'us-ia', 'Iowa'),
('us', 'us-id', 'Idaho'),
('us', 'us-il', 'Illinois'),
('us', 'us-in', 'Indiana'),
('us', 'us-ks', 'Kansas'),
('us', 'us-ky', 'Kentucky'),
('us', 'us-la', 'Louisiana'),
('us', 'us-ma', 'Massachusetts'),
('us', 'us-md', 'Maryland'),
('us', 'us-me', 'Maine'),
('us', 'us-mi', 'Michigan'),
('us', 'us-mn', 'Minnesota'),
('us', 'us-mo', 'Missouri'),
('us', 'us-ms', 'Mississippi'),
('us', 'us-mt', 'Montana'),
('us', 'us-nc', 'North Carolina'),
('us', 'us-nd', 'North Dakota'),
('us', 'us-ne', 'Nebraska'),
('us', 'us-nh', 'New Hampshire'),
('us', 'us-nj', 'New Jersey'),
('us', 'us-nm', 'New Mexico'),
('us', 'us-nv', 'Nevada'),
('us', 'us-ny', 'New York'),
('us', 'us-oh', 'Ohio'),
('us', 'us-ok', 'Oklahoma'),
('us', 'us-or', 'Oregon'),
('us', 'us-pa', 'Pennsylvania'),
('us', 'us-ri', 'Rhode Island'),
('us', 'us-sc', 'South Carolina'),
('us', 'us-sd', 'South Dakota'),
('us', 'us-tn', 'Tennessee'),
('us', 'us-tx', 'Texas'),
('us', 'us-ut', 'Utah'),
('us', 'us-va', 'Virginia'),
('us', 'us-vt', 'Vermont'),
('us', 'us-wa', 'Washington'),
('us', 'us-wi', 'Wisconsin'),
('us', 'us-wv', 'West Virginia'),
('us', 'us-wy', 'Wyoming');


DELETE FROM `wp_country_province` WHERE `code_country` = 'ca';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('ca', 'ca-ab', 'Alberta'),
('ca', 'ca-bc', 'British Columbia'),
('ca', 'ca-mb', 'Manitoba'),
('ca', 'ca-nb', 'New Brunswick'),
('ca', 'ca-nl', 'Newfoundland and Labrador'),
('ca', 'ca-ns', 'Nova Scotia'),
('ca', 'ca-nt', 'Northwest Territories'),
('ca', 'ca-nu', 'Nunavut'),
('ca', 'ca-on', 'Ontario'),
('ca', 'ca-pe', 'Prince Edward Island'),
('ca', 'ca-qc', 'Quebec'),
('ca', 'ca-sk', 'Saskatchewan'),
('ca', 'ca-yt', 'Yukon');



DELETE FROM `wp_country_province` WHERE `code_country` = 'mx';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('mx', 'mx-agu', 'Aguascalientes'),
('mx', 'mx-bcn', 'Baja California'),
('mx', 'mx-bcs', 'Baja California Sur'),
('mx', 'mx-cam', 'Campeche'),
('mx', 'mx-chh', 'Chihuahua'),
('mx', 'mx-chp', 'Chiapas'),
('mx', 'mx-cmx', 'Mexican Federal District'),
('mx', 'mx-coa', 'Coahuila'),
('mx', 'mx-col', 'Colima'),
('mx', 'mx-dur', 'Durango'),
('mx', 'mx-gro', 'Guerrero'),
('mx', 'mx-gua', 'Guanajuato'),
('mx', 'mx-hid', 'Hidalgo'),
('mx', 'mx-jal', 'Jalisco'),
('mx', 'mx-mex', 'Mexico'),
('mx', 'mx-mdf', 'Mexico D.F.'),
('mx', 'mx-mic', 'Michoacan'),
('mx', 'mx-mor', 'Morelos'),
('mx', 'mx-nay', 'Nayarit'),
('mx', 'mx-nle', 'Nuevo Leon'),
('mx', 'mx-oax', 'Oaxaca'),
('mx', 'mx-pue', 'Puebla'),
('mx', 'mx-que', 'Queretaro'),
('mx', 'mx-roo', 'Quintana Roo'),
('mx', 'mx-sin', 'Sinaloa'),
('mx', 'mx-slp', 'San Luis Potosi'),
('mx', 'mx-son', 'Sonora'),
('mx', 'mx-tab', 'Tabasco'),
('mx', 'mx-tam', 'Tamaulipas'),
('mx', 'mx-tla', 'Tlaxcala'),
('mx', 'mx-ver', 'Veracruz'),
('mx', 'mx-yuc', 'Yucatan'),
('mx', 'mx-zac', 'Zacatecas');

DELETE FROM `wp_country_province` WHERE `code_country` = 'in';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('in', 'in-an', 'Andaman and Nicobar Islands'),
('in', 'in-ap', 'Andhra Pradesh'),
('in', 'in-ar', 'Arunachal Pradesh'),
('in', 'in-as', 'Assam'),
('in', 'in-br', 'Bihar'),
('in', 'in-ch', 'Chandigarh'),
('in', 'in-ct', 'Chhattisgarh'),
('in', 'in-dd', 'Daman and Diu'),
('in', 'in-dl', 'National Capital Territory of Delhi'),
('in', 'in-dn', 'Dadra and Nagar Haveli'),
('in', 'in-ga', 'Goa'),
('in', 'in-gj', 'Gujarat'),
('in', 'in-hp', 'Himachal Pradesh'),
('in', 'in-hr', 'Haryana'),
('in', 'in-jh', 'Jharkhand'),
('in', 'in-jk', 'Jammu and Kashmir'),
('in', 'in-ka', 'Karnataka'),
('in', 'in-kl', 'Kerala'),
('in', 'in-ld', 'Lakshadweep'),
('in', 'in-mh', 'Maharashtra'),
('in', 'in-ml', 'Meghalaya'),
('in', 'in-mn', 'Manipur'),
('in', 'in-mp', 'Madhya Pradesh'),
('in', 'in-mz', 'Mizoram'),
('in', 'in-nl', 'Nagaland'),
('in', 'in-or', 'Orissa'),
('in', 'in-pb', 'Punjab'),
('in', 'in-py', 'Puducherry'),
('in', 'in-rj', 'Rajasthan'),
('in', 'in-sk', 'Sikkim'),
('in', 'in-tg', 'Telengana'),
('in', 'in-tn', 'Tamil Nadu'),
('in', 'in-tr', 'Tripura'),
('in', 'in-up', 'Uttar Pradesh'),
('in', 'in-ut', 'Uttarakhand'),
('in', 'in-wb', 'West Bengal');



DELETE FROM `wp_country_province` WHERE `code_country` = 'my';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('my', 'JHR', 'Johor'),
('my', 'KDH', 'Kedah'),
('my', 'KTN', 'Kelantan'),
('my', 'MLK', 'Melaka'),
('my', 'NSN', 'Negeri Sembilan'),
('my', 'PHG', 'Pahang'),
('my', 'PNG', 'Pulau Pinang'),
('my', 'PRK', 'Perak'),
('my', 'PLS', 'Perlis'),
('my', 'SGR', 'Selangor'),
('my', 'TRG', 'Terengganu'),
('my', 'SBH', 'Sabah'),
('my', 'SRW', 'Sarawak'),
('my', 'KUL', 'Kuala Lumpur'),
('my', 'LBN', 'Labuan'),
('my', 'PJY', 'Putrajaya');


DELETE FROM `wp_country_province` WHERE `code_country` = 'at';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('at', 'at-1', 'Burgenland'),
('at', 'at-2', 'Carinthia'),
('at', 'at-3', 'Lower Austria'),
('at', 'at-4', 'Upper Austria'),
('at', 'at-5', 'Salzburg'),
('at', 'at-6', 'Styria'),
('at', 'at-7', 'Tyrol'),
('at', 'at-8', 'Vorarlberg'),
('at', 'at-9', 'Vienna');


DELETE FROM `wp_country_province` WHERE `code_country` = 'be';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('be', 'be-01', 'Antwerpen'),
('be', 'be-03', 'Brabant'),
('be', 'be-04', 'Brabant wallon'),
('be', 'be-05', 'Brussels'),
('be', 'be-06', 'Hainaut'),
('be', 'be-07', 'Liege'),
('be', 'be-08', 'Limburg'),
('be', 'be-09', 'Luxembourg'),
('be', 'be-10', 'Namur'),
('be', 'be-12', 'Oost-Vlaanderen'),
('be', 'be-13', 'West-Vlaanderen'),
('be', 'be-14', 'Vlaams');


DELETE FROM `wp_country_province` WHERE `code_country` = 'es';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('es', 'es-01', 'Alava (Pais Vasco)'),
('es', 'es-02', 'Albacete (Castilla-La Mancha)'),
('es', 'es-03', 'Alicante (Comunidad Valenciana)'),
('es', 'es-04', 'Almeria (Andalucia)'),
('es', 'es-05', 'Asturias (Asturias)'),
('es', 'es-06', 'Avila (Castilla-Leon)'),
('es', 'es-07', 'Badajoz (Extremadura)'),
('es', 'es-08', 'Barcelona (Catalunya)'),
('es', 'es-09', 'Burgos (Castilla-Leon)'),
('es', 'es-10', 'Caceres (Extremadura)'),
('es', 'es-11', 'Cadiz (Andalucia)'),
('es', 'es-12', 'Cantabria (Cantabria)'),
('es', 'es-13', 'Castellon (Comunidad Valenciana)'),
('es', 'es-14', 'Ceuta (Ceuta)'),
('es', 'es-15', 'Ciudad Real (Castilla-La Mancha)'),
('es', 'es-16', 'Cordoba    (Andalucia)'),
('es', 'es-17', 'La Coruna (Galicia)'),
('es', 'es-18', 'Cuenca (Castilla-La Mancha)'),
('es', 'es-19', 'Girona (Cataluya)'),
('es', 'es-20', 'Granada (Andalucia)'),
('es', 'es-21', 'Guadalajara (Castilla-La Mancha)'),
('es', 'es-22', 'Guipuzcoa (Pais Vasco)'),
('es', 'es-23', 'Huelva (Andalucia)'),
('es', 'es-24', 'Huesca (Aragon)'),
('es', 'es-25', 'Islas Baleares (Islas Baleares)'),
('es', 'es-26', 'Jaen (Andalucia)'),
('es', 'es-27', 'La Rioja (La Rioja)'),
('es', 'es-28', 'Leon (Castilla-Leon)'),
('es', 'es-29', 'Lleida (Catalunya)'),
('es', 'es-30', 'Lugo (Galicia)'),
('es', 'es-31', 'Madrid (Madrid)'),
('es', 'es-32', 'Malaga (Andalucia)'),
('es', 'es-33', 'Melilla (Melilla)'),
('es', 'es-34', 'Murcia (Region de Murcia)'),
('es', 'es-35', 'Navarra (Navarra)'),
('es', 'es-36', 'Orense (Galicia)'),
('es', 'es-37', 'Palencia (Castilla-Leon)'),
('es', 'es-38', 'Las Palmas (Islas Canarias)'),
('es', 'es-39', 'Pontevedra    (Galicia)'),
('es', 'es-40', 'Salamanca (Castilla-Leon)'),
('es', 'es-41', 'Santa Cruz de Tenerife (Islas Canarias)'),
('es', 'es-42', 'Segovia (Castilla-Leon)'),
('es', 'es-43', 'Sevilla (Andalucia)'),
('es', 'es-44', 'Soria (Castilla-Leon)'),
('es', 'es-45', 'Tarragona (Catalunya)'),
('es', 'es-46', 'Teruel (Aragon)'),
('es', 'es-47', 'Toledo (Castilla-La Mancha)'),
('es', 'es-48', 'Valencia (Comunidad Valenciana)'),
('es', 'es-49', 'Valladolid (Castilla-Leon)'),
('es', 'es-50', 'Zamora (Castilla-Leon)'),
('es', 'es-51', 'Zaragoza (Aragon)');


DELETE FROM `wp_country_province` WHERE `code_country` = 'jp';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('jp', 'jp-01', 'Hokkaido'),
('jp', 'jp-02', 'Aomori'),
('jp', 'jp-03', 'Iwate'),
('jp', 'jp-04', 'Miyagi'),
('jp', 'jp-05', 'Akita'),
('jp', 'jp-06', 'Yamagata'),
('jp', 'jp-07', 'Fukushima'),
('jp', 'jp-08', 'Ibaraki'),
('jp', 'jp-09', 'Tochigi'),
('jp', 'jp-10', 'Gunma'),
('jp', 'jp-11', 'Saitama'),
('jp', 'jp-12', 'Chiba'),
('jp', 'jp-13', 'Tokyo'),
('jp', 'jp-14', 'Kanagawa'),
('jp', 'jp-15', 'Niigata'),
('jp', 'jp-16', 'Toyama'),
('jp', 'jp-17', 'Ishikawa'),
('jp', 'jp-18', 'Fukui'),
('jp', 'jp-19', 'Yamanashi'),
('jp', 'jp-20', 'Nagano'),
('jp', 'jp-21', 'Gifu'),
('jp', 'jp-22', 'Shizuoka'),
('jp', 'jp-23', 'Aichi'),
('jp', 'jp-24', 'Mie'),
('jp', 'jp-25', 'Shiga'),
('jp', 'jp-26', 'Kyoto'),
('jp', 'jp-27', 'Osaka'),
('jp', 'jp-28', 'Hyogo'),
('jp', 'jp-29', 'Nara'),
('jp', 'jp-30', 'Wakayama'),
('jp', 'jp-31', 'Tottori'),
('jp', 'jp-32', 'Shimane'),
('jp', 'jp-33', 'Okayama'),
('jp', 'jp-34', 'Hiroshima'),
('jp', 'jp-35', 'Yamaguchi'),
('jp', 'jp-36', 'Tokushima'),
('jp', 'jp-37', 'Kagawa'),
('jp', 'jp-38', 'Ehime'),
('jp', 'jp-39', 'Kochi'),
('jp', 'jp-40', 'Fukuoka'),
('jp', 'jp-41', 'Saga'),
('jp', 'jp-42', 'Nagasaki'),
('jp', 'jp-43', 'Kumamoto'),
('jp', 'jp-44', 'Oita'),
('jp', 'jp-45', 'Miyazaki'),
('jp', 'jp-46', 'Kagoshima'),
('jp', 'jp-47', 'Okinawa');



DELETE FROM `wp_country_province` WHERE `code_country` = 'kr';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('kr', 'kr-01', 'Busan'),
('kr', 'kr-02', 'Chungbuk'),
('kr', 'kr-03', 'Chungnam'),
('kr', 'kr-04', 'Daegu'),
('kr', 'kr-05', 'Daejeon'),
('kr', 'kr-06', 'Gangwon'),
('kr', 'kr-07', 'Gwangju'),
('kr', 'kr-08', 'Gyeongnam'),
('kr', 'kr-09', 'Gyeongbuk'),
('kr', 'kr-10', 'Gyeonggi'),
('kr', 'kr-11', 'Jeju'),
('kr', 'kr-12', 'Jeonbuk'),
('kr', 'kr-13', 'Jeonnam'),
('kr', 'kr-14', 'Incheon'),
('kr', 'kr-15', 'Seoul'),
('kr', 'kr-16', 'Ulsan');




DELETE FROM `wp_country_province` WHERE `code_country` = 'fr';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('fr', 'fr-01', '01 Ain'),
('fr', 'fr-02', '02 Aisne'),
('fr', 'fr-03', '03 Allier'),
('fr', 'fr-04', '04 Alpes-de-Haute-Provence'),
('fr', 'fr-05', '05 Hautes-Alpes'),
('fr', 'fr-06', '06 Alpes-Maritimes'),
('fr', 'fr-07', '07 Ardeche'),
('fr', 'fr-08', '08 Ardennes'),
('fr', 'fr-09', '09 Ariege'),
('fr', 'fr-10', '10 Aube'),
('fr', 'fr-11', '11 Aude'),
('fr', 'fr-12', '12 Aveyron'),
('fr', 'fr-13', '13 Bouches-du-Rhone'),
('fr', 'fr-14', '14 Calvados'),
('fr', 'fr-15', '15 Cantal'),
('fr', 'fr-16', '16 Charente'),
('fr', 'fr-17', '17 Charente-Maritime'),
('fr', 'fr-18', '18 Cher'),
('fr', 'fr-19', '19 Correze'),
('fr', 'fr-21', '21 Cote-d’Or'),
('fr', 'fr-22', '22 Cotes-d’Armor'),
('fr', 'fr-23', '23 Creuse'),
('fr', 'fr-24', '24 Dordogne'),
('fr', 'fr-25', '25 Doubs'),
('fr', 'fr-26', '26 Drome'),
('fr', 'fr-27', '27 Eure'),
('fr', 'fr-28', '28 Eure-et-Loir'),
('fr', 'fr-29', '29 Finistere'),
('fr', 'fr-2a', '2A Corse-du-Sud'),
('fr', 'fr-2b', '2B Haute-Corse'),
('fr', 'fr-30', '30 Gard'),
('fr', 'fr-31', '31 Haute-Garonne'),
('fr', 'fr-32', '32 Gers'),
('fr', 'fr-33', '33 Gironde'),
('fr', 'fr-34', '34 Herault'),
('fr', 'fr-35', '35 Ille-et-Vilaine'),
('fr', 'fr-36', '36 Indre'),
('fr', 'fr-37', '37 Indre-et-Loire'),
('fr', 'fr-38', '38 Isere'),
('fr', 'fr-39', '39 Jura'),
('fr', 'fr-40', '40 Landes'),
('fr', 'fr-41', '41 Loir-et-Cher'),
('fr', 'fr-42', '42 Loire'),
('fr', 'fr-43', '43 Haute-Loire'),
('fr', 'fr-44', '44 Loire-Atlantique'),
('fr', 'fr-45', '45 Loiret'),
('fr', 'fr-46', '46 Lot'),
('fr', 'fr-47', '47 Lot-et-Garonne'),
('fr', 'fr-48', '48 Lozere'),
('fr', 'fr-49', '49 Maine-et-Loire'),
('fr', 'fr-50', '50 Manche'),
('fr', 'fr-51', '51 Marne'),
('fr', 'fr-52', '52 Haute-Marne'),
('fr', 'fr-53', '53 Mayenne'),
('fr', 'fr-54', '54 Meurthe-et-Moselle'),
('fr', 'fr-55', '55 Meuse'),
('fr', 'fr-56', '56 Morbihan'),
('fr', 'fr-57', '57 Moselle'),
('fr', 'fr-58', '58 Nievre'),
('fr', 'fr-59', '59 Nord'),
('fr', 'fr-60', '60 Oise'),
('fr', 'fr-61', '61 Ornene'),
('fr', 'fr-62', '62 Pas-de-Calais'),
('fr', 'fr-63', '63 Puy-de-Dome'),
('fr', 'fr-64', '64 Pyrenees-Atlantiques'),
('fr', 'fr-65', '65 Hautes-Pyrenees'),
('fr', 'fr-66', '66 Pyrenees-Orientales'),
('fr', 'fr-67', '67 Bas-Rhin'),
('fr', 'fr-68', '68 Haut-Rhin'),
('fr', 'fr-69', '69 Rhone'),
('fr', 'fr-70', '70 Haute-Saone'),
('fr', 'fr-71', '71 Saone-et-Loire'),
('fr', 'fr-72', '72 Sarthe'),
('fr', 'fr-73', '73 Savoie'),
('fr', 'fr-74', '74 Haute-Savoie'),
('fr', 'fr-75', '75 Paris'),
('fr', 'fr-76', '76 Seine-Maritime'),
('fr', 'fr-77', '77 Seine-et-Marne'),
('fr', 'fr-78', '78 Yvelines'),
('fr', 'fr-79', '79 Deux-Sevres'),
('fr', 'fr-80', '80 Somme'),
('fr', 'fr-81', '81 Tarn'),
('fr', 'fr-82', '82 Tarn-et-Garonne'),
('fr', 'fr-83', '83 Var'),
('fr', 'fr-84', '84 Vaucluse'),
('fr', 'fr-85', '85 Vendee'),
('fr', 'fr-86', '86 Vienne'),
('fr', 'fr-87', '87 Haute-Vienne'),
('fr', 'fr-88', '88 Vosges'),
('fr', 'fr-89', '89 Yonne'),
('fr', 'fr-90', '90 Territoire de Belfort'),
('fr', 'fr-91', '91 Essonne'),
('fr', 'fr-92', '92 Hauts-de-Seine'),
('fr', 'fr-93', '93 Seine-Saint-Denis'),
('fr', 'fr-94', '94 Val-de-Marne'),
('fr', 'fr-95', '95 Val-d''Oise');



DELETE FROM `wp_country_province` WHERE `code_country` = 'it';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('it', 'it-01', 'Abruzzo'),
('it', 'it-02', 'Val d’Aoste'),
('it', 'it-03', 'Puglia'),
('it', 'it-04', 'Basilicata'),
('it', 'it-05', 'Calabria'),
('it', 'it-06', 'Campania'),
('it', 'it-07', 'Emilia-Romagna'),
('it', 'it-08', 'Friuli-Venezia Giulia'),
('it', 'it-09', 'Lazio'),
('it', 'it-10', 'Liguria'),
('it', 'it-11', 'Lombardia'),
('it', 'it-12', 'Marche'),
('it', 'it-13', 'Molise'),
('it', 'it-14', 'Piemonte'),
('it', 'it-15', 'Sardegna'),
('it', 'it-16', 'Sicilia'),
('it', 'it-17', 'Trentino-Alto Adige'),
('it', 'it-18', 'Toscana'),
('it', 'it-19', 'Umbria'),
('it', 'it-20', 'Veneto');



DELETE FROM `wp_country_province` WHERE `code_country` = 'pe';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('pe', 'pe-ama', 'Amazonas'),
('pe', 'pe-anc', 'Ancash'),
('pe', 'pe-apu', 'Apurimac'),
('pe', 'pe-are', 'Arequipa'),
('pe', 'pe-aya', 'Ayacucho'),
('pe', 'pe-caj', 'Cajamarca'),
('pe', 'pe-cal', 'Callao'),
('pe', 'pe-cus', 'Cusco'),
('pe', 'pe-huc', 'Huanuco'),
('pe', 'pe-huv', 'Huancavelica'),
('pe', 'pe-ica', 'Ica'),
('pe', 'pe-jun', 'Junin'),
('pe', 'pe-lal', 'La Libertad'),
('pe', 'pe-lam', 'Lambayeque'),
('pe', 'pe-lim', 'Lima'),
('pe', 'pe-lor', 'Loreto'),
('pe', 'pe-mdd', 'Madre de Dios'),
('pe', 'pe-moq', 'Moquegua'),
('pe', 'pe-pas', 'Pasco'),
('pe', 'pe-piu', 'Piura'),
('pe', 'pe-pun', 'Puno'),
('pe', 'pe-sam', 'San Martin'),
('pe', 'pe-tac', 'Tacna'),
('pe', 'pe-tum', 'Tumbes'),
('pe', 'pe-uca', 'Ucayali');




DELETE FROM `wp_country_province` WHERE `code_country` = 'ch';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('ch', 'ch-ag', 'Aargau'),
('ch', 'ch-ai', 'Appenzell Innerrhoden'),
('ch', 'ch-ar', 'Appenzell Ausserrhoden'),
('ch', 'ch-be', 'Bern'),
('ch', 'ch-bl', 'Basel-Landschaft'),
('ch', 'ch-bs', 'Basel-Stadt'),
('ch', 'ch-fr', 'Fribourg'),
('ch', 'ch-ge', 'Geneve'),
('ch', 'ch-gl', 'Glarus'),
('ch', 'ch-gr', 'Graubuenden'),
('ch', 'ch-ju', 'Jura'),
('ch', 'ch-lu', 'Luzern'),
('ch', 'ch-ne', 'Neuchatel'),
('ch', 'ch-nw', 'Nidwalden'),
('ch', 'ch-ow', 'Obwalden'),
('ch', 'ch-sg', 'St. Gallen'),
('ch', 'ch-sh', 'Schaffhausen'),
('ch', 'ch-so', 'Solothurn'),
('ch', 'ch-sz', 'Schwyz'),
('ch', 'ch-tg', 'Thurgau'),
('ch', 'ch-ti', 'Ticino'),
('ch', 'ch-ur', 'Uri'),
('ch', 'ch-vd', 'Vaud'),
('ch', 'ch-vs', 'Valais'),
('ch', 'ch-zg', 'Zug'),
('ch', 'ch-zh', 'Zuerich');



DELETE FROM `wp_country_province` WHERE `code_country` = 'de';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('de', 'de-bb', 'Brandenburg'),
('de', 'de-be', 'Berlin'),
('de', 'de-bw', 'Baden-Wuerttemberg'),
('de', 'de-by', 'Bayern'),
('de', 'de-hb', 'Bremen'),
('de', 'de-he', 'Hessen'),
('de', 'de-hh', 'Hamburg'),
('de', 'de-mv', 'Mecklenburg-Vorpommern'),
('de', 'de-ni', 'Niedersachsen'),
('de', 'de-nw', 'Nordrhein-Westfalen'),
('de', 'de-rp', 'Rheinland-Pfalz'),
('de', 'de-sh', 'Schleswig-Holstein'),
('de', 'de-sl', 'Saarland'),
('de', 'de-sn', 'Sachsen'),
('de', 'de-st', 'Sachsen-Anhalt'),
('de', 'de-th', 'Thueringen');



DELETE FROM `wp_country_province` WHERE `code_country` = 'br';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('br', 'br-ac', 'Acre'),
('br', 'br-al', 'Alagoas'),
('br', 'br-am', 'Amazonas'),
('br', 'br-ap', 'Amapa'),
('br', 'br-ba', 'Bahia'),
('br', 'br-ce', 'Ceara'),
('br', 'br-df', 'Distrito Federal'),
('br', 'br-es', 'Espirito Santo'),
('br', 'br-go', 'Goias'),
('br', 'br-ma', 'Maranhao'),
('br', 'br-mg', 'Minas Gerais'),
('br', 'br-ms', 'Mato Grosso do Sul'),
('br', 'br-mt', 'Mato Grosso'),
('br', 'br-pa', 'Para'),
('br', 'br-pb', 'Paraiba'),
('br', 'br-pe', 'Pernambuco'),
('br', 'br-pi', 'Piaui'),
('br', 'br-pr', 'Parana'),
('br', 'br-rj', 'Rio de Janeiro'),
('br', 'br-rn', 'Rio Grande do Norte'),
('br', 'br-ro', 'Rondonia'),
('br', 'br-rr', 'Roraima'),
('br', 'br-rs', 'Rio Grande do Sul'),
('br', 'br-sc', 'Santa Catarina'),
('br', 'br-se', 'Sergipe'),
('br', 'br-sp', 'Sao Paulo'),
('br', 'br-to', 'Tocantins');



DELETE FROM `wp_country_province` WHERE `code_country` = 'cn';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('cn', 'cn-11', 'Beijing'),
('cn', 'cn-12', 'Tianjin'),
('cn', 'cn-13', 'Hebei'),
('cn', 'cn-14', 'Shanxi'),
('cn', 'cn-15', 'Inner Mongolia Autonomous Region'),
('cn', 'cn-21', 'Liaoning'),
('cn', 'cn-22', 'Jilin'),
('cn', 'cn-23', 'Heilongjiang'),
('cn', 'cn-31', 'Shanghai'),
('cn', 'cn-32', 'Jiangsu'),
('cn', 'cn-33', 'Zhejiang'),
('cn', 'cn-34', 'Anhui'),
('cn', 'cn-35', 'Fujian'),
('cn', 'cn-36', 'Jiangxi'),
('cn', 'cn-37', 'Shandong'),
('cn', 'cn-41', 'Henan'),
('cn', 'cn-42', 'Hubei'),
('cn', 'cn-43', 'Hunan'),
('cn', 'cn-44', 'Guangdong'),
('cn', 'cn-45', 'Guangxi'),
('cn', 'cn-46', 'Hainan'),
('cn', 'cn-50', 'Chongqing'),
('cn', 'cn-51', 'Sichuan'),
('cn', 'cn-52', 'Guizhou'),
('cn', 'cn-53', 'Yunnan'),
('cn', 'cn-54', 'Neimenggu'),
('cn', 'cn-61', 'Shaanxi'),
('cn', 'cn-62', 'Gansu'),
('cn', 'cn-63', 'Qinghai'),
('cn', 'cn-64', 'Ningxia'),
('cn', 'cn-65', 'Xinjiang'),
('cn', 'cn-71', 'Xianggang'),
('cn', 'cn-91', 'Aomen'),
('cn', 'cn-92', 'Xizang');



DELETE FROM `wp_country_province` WHERE `code_country` = 'mn';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('mn', 'mn-035', 'Orhon'),
('mn', 'mn-037', 'Darhan uul'),
('mn', 'mn-039', 'Hentiy'),
('mn', 'mn-041', 'Hovsgol'),
('mn', 'mn-043', 'Hovd'),
('mn', 'mn-046', 'Uvs'),
('mn', 'mn-047', 'Tov'),
('mn', 'mn-049', 'Selenge'),
('mn', 'mn-051', 'Suhbaatar'),
('mn', 'mn-053', 'Omnogovi'),
('mn', 'mn-055', 'Ovorhangay'),
('mn', 'mn-057', 'Dzavhan'),
('mn', 'mn-059', 'DundgovL'),
('mn', 'mn-061', 'Dornod'),
('mn', 'mn-063', 'Dornogov'),
('mn', 'mn-064', 'Govi-Sumber'),
('mn', 'mn-065', 'Govi-Altay'),
('mn', 'mn-067', 'Bulgan'),
('mn', 'mn-069', 'Bayanhongor'),
('mn', 'mn-071', 'Bayan-Olgiy'),
('mn', 'mn-073', 'Arhangay'),
('mn', 'mn-1', 'Ulanbaatar');



DELETE FROM `wp_country_province` WHERE `code_country` = 'co';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('co', 'co-ama', 'Amazonas'),
('co', 'co-ant', 'Antioquia'),
('co', 'co-ara', 'Arauca'),
('co', 'co-atl', 'Atlantico'),
('co', 'co-bol', 'Bolivar'),
('co', 'co-boy', 'Boyaca'),
('co', 'co-cal', 'Caldas'),
('co', 'co-caq', 'Caqueta'),
('co', 'co-cas', 'Casanare'),
('co', 'co-cau', 'Cauca'),
('co', 'co-ces', 'Cesar'),
('co', 'co-cho', 'Choco'),
('co', 'co-cor', 'Cordoba'),
('co', 'co-cun', 'Cundinamarca'),
('co', 'co-dc', 'Bogota (DC)'),
('co', 'co-gua', 'Guainia'),
('co', 'co-guv', 'Guaviare'),
('co', 'co-hui', 'Huila'),
('co', 'co-lag', 'La Guajira'),
('co', 'co-mag', 'Magdalena'),
('co', 'co-met', 'Meta'),
('co', 'co-nar', 'Narino'),
('co', 'co-nsa', 'Norte de Santander'),
('co', 'co-put', 'Putumayo'),
('co', 'co-qui', 'Quindio'),
('co', 'co-ris', 'Risaralda'),
('co', 'co-san', 'Santander'),
('co', 'co-sap', 'San Andres, Providencia & Santa Catalina'),
('co', 'co-suc', 'Sucre'),
('co', 'co-tol', 'Tolima'),
('co', 'co-vac', 'Valle del Cauca'),
('co', 'co-vau', 'Vaupes'),
('co', 'co-vid', 'Vichada');



DELETE FROM `wp_country_province` WHERE `code_country` = 'il';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('il', 'il-d', 'Southern'),
('il', 'il-ha', 'Haifa'),
('il', 'il-jm', 'Jerusalem'),
('il', 'il-m', 'Center'),
('il', 'il-ta', 'Tel Aviv'),
('il', 'il-z', 'North');




DELETE FROM `wp_country_province` WHERE `code_country` = 'nl';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('nl', 'nl-dr', 'Drenthe'),
('nl', 'nl-fl', 'Flevoland'),
('nl', 'nl-fr', 'Fryslan'),
('nl', 'nl-ge', 'Gelderland'),
('nl', 'nl-gr', 'Groningen'),
('nl', 'nl-li', 'Limburg'),
('nl', 'nl-nb', 'Noord Brabant'),
('nl', 'nl-nh', 'Noord Holland'),
('nl', 'nl-ov', 'Overijssel'),
('nl', 'nl-ut', 'Utrecht'),
('nl', 'nl-ze', 'Zeeland'),
('nl', 'nl-zh', 'Zuid Holland');



DELETE FROM `wp_country_province` WHERE `code_country` = 'dk';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('dk', 'dk-81', 'Nordjylland'),
('dk', 'dk-82', 'Midtjylland'),
('dk', 'dk-83', 'Syddanmark'),
('dk', 'dk-84', 'Hovedstaden'),
('dk', 'dk-85', 'Sjaelland');


DELETE FROM `wp_country_province` WHERE `code_country` = 'nz';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('nz', 'nz-auk', 'Auckland'),
('nz', 'nz-bop', 'Bay of Plenty'),
('nz', 'nz-can', 'Canterbury'),
('nz', 'nz-cit', 'Stewart Islands'),
('nz', 'nz-gis', 'Coromandel'),
('nz', 'nz-hkb', 'Hawkes Bay'),
('nz', 'nz-mbh', 'Marlborough'),
('nz', 'nz-mwt', 'Wanganui'), 
('nz', 'nz-nsn', 'Nelson'),
('nz', 'nz-ntl', 'Northland'),
('nz', 'nz-ota', 'Otago'),
('nz', 'nz-stl', 'Southland'),
('nz', 'nz-eac', 'East Coast'),
('nz', 'nz-tki', 'Taranaki'),
('nz', 'nz-wgn', 'Wellington'),
('nz', 'nz-wko', 'Waikato'),
('nz', 'nz-cep', 'Central Plateau'),
('nz', 'nz-wai', 'Wairarapa'),
('nz', 'nz-fio', 'Fiordland'),
('nz', 'nz-wtc', 'West Coast');



DELETE FROM `wp_country_province` WHERE `code_country` = 'se';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('se', 'se-ab', 'Stockholm'),
('se', 'se-ac', 'Vasterbotten'),
('se', 'se-bd', 'Norrbotten'),
('se', 'se-c', 'Uppsala'),
('se', 'se-d', 'Sodermanland'),
('se', 'se-e', 'Ostergotland'),
('se', 'se-f', 'Jonkoping'),
('se', 'se-g', 'Kronoberg'),
('se', 'se-h', 'Kalmar'),
('se', 'se-i', 'Gotland'),
('se', 'se-k', 'Blekinge'),
('se', 'se-m', 'Skane'),
('se', 'se-n', 'Halland'),
('se', 'se-o', 'Vastra Gotaland'),
('se', 'se-s', 'Varmland'),
('se', 'se-t', 'Orebro'),
('se', 'se-u', 'Vasternorrland'),
('se', 'se-w', 'Dalarnas'),
('se', 'se-x', 'Gavleborg'),
('se', 'se-y', 'Vastmanland'),
('se', 'se-z', 'Jamtland');



DELETE FROM `wp_country_province` WHERE `code_country` = 'gb';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('gb', 'gb-abc', 'N.Ireland: Armagh'),
('gb', 'gb-abd', 'Scotland: Aberdeenshire'),
('gb', 'gb-arg', 'Scotland: Argyllshire'),
('gb', 'gb-agy', 'Wales: Anglesey/Sir Fon'),
('gb', 'gb-and', 'N.Ireland: Down'),
('gb', 'gb-ans', 'Scotland: Angus/Forfarshire'),
('gb', 'gb-ban', 'Scotland: Banffshire'),
('gb', 'gb-brk', 'Wales: Brecknockshire/Sir Frycheiniog'),
('gb', 'gb-bur', 'Scotland: Buteshire'),
('gb', 'gb-ber', 'Scotland: Berwickshire'),
('gb', 'gb-bkm', 'England: Buckinghamshire'),
('gb', 'gb-cam', 'England: Cambridgeshire'),
('gb', 'gb-cae', 'Wales: Caernarfonshire/Sir Gaernarfon'),
('gb', 'gb-cro', 'Scotland: Cromartyshire'),
('gb', 'gb-cbf', 'England: Bedfordshire'),
('gb', 'gb-cgn', 'Wales: Cardiganshire/Ceredigion'),
('gb', 'gb-che', 'England: Cheshire'),
('gb', 'gb-cum', 'England: Cumberland'),
('gb', 'gb-clk', 'Scotland: Clackmannanshire'),
('gb', 'gb-cai', 'Scotland: Caithness'),
('gb', 'gb-cmn', 'Wales: Carmarthenshire/Sir Gaerfyrddin'),
('gb', 'gb-con', 'England: Cornwall'),
('gb', 'gb-dby', 'England: Derbyshire'),
('gb', 'gb-den', 'Wales: Denbighshire/Sir Ddinbych'),
('gb', 'gb-dev', 'England: Devon'),
('gb', 'gb-dum', 'Scotland: Dumfriesshire'),
('gb', 'gb-dor', 'England: Dorset'),
('gb', 'gb-dur', 'England: Durham'),
('gb', 'gb-eay', 'Scotland: Ayrshire'),
('gb', 'gb-edu', 'Scotland: Dunbartonshire/Dumbartonshire'),
('gb', 'gb-eln', 'Scotland: East Lothian/Haddingtonshire'),
('gb', 'gb-edn', 'Scotland: Midlothian/Edinburghshire'),
('gb', 'gb-ery', 'England: East Yorkshire'),
('gb', 'gb-ess', 'England: Essex'),
('gb', 'gb-esx', 'England: Sussex'),
('gb', 'gb-fif', 'Scotland: Fife'),
('gb', 'gb-fln', 'Wales: Flintshire/Sir Fflint'),
('gb', 'gb-fmo', 'N.Ireland: Fermanagh'),
('gb', 'gb-gls', 'England: Gloucestershire'),
('gb', 'gb-gwn', 'England: Huntingdonshire'),
('gb', 'gb-ham', 'England: Hampshire'),
('gb', 'gb-hef', 'England: Herefordshire'),
('gb', 'gb-hrt', 'England: Hertfordshire'),
('gb', 'gb-inv', 'Scotland: Inverness-shire'),
('gb', 'gb-ken', 'England: Kent'),
('gb', 'gb-kin', 'Scotland: Kincardineshire'),
('gb', 'gb-krk', 'Scotland: Kirkcudbrightshire'),
('gb', 'gb-lan', 'England: Lancashire'),
('gb', 'gb-lec', 'England: Leicestershire'),
('gb', 'gb-lin', 'England: Lincolnshire'),
('gb', 'gb-liv', 'N.Ireland: Londonderry'),
('gb', 'gb-mer', 'Wales: Merioneth/Meirionnydd'),
('gb', 'gb-man', 'England: Middlesex'),
('gb', 'gb-mor', 'Scotland: Morayshire'),
('gb', 'gb-mea', 'N.Ireland: Antrim'),
('gb', 'gb-mon', 'Wales: Monmouthshire/Sir Fynwy'),
('gb', 'gb-mot', 'Wales: Montgomeryshire/Sir Drefaldwyn'),
('gb', 'gb-nbl', 'England: Northumberland'),
('gb', 'gb-nfk', 'England: Norfolk'),
('gb', 'gb-nai', 'Scotland: Nairnshire'),
('gb', 'gb-nlk', 'Scotland: Lanarkshire'),
('gb', 'gb-nth', 'England: Northamptonshire'),
('gb', 'gb-ntt', 'England: Nottinghamshire'),
('gb', 'gb-nty', 'England: NorthYorkshire'),
('gb', 'gb-ork', 'Scotland: Orkney'),
('gb', 'gb-oxf', 'England: Oxfordshire'),
('gb', 'gb-pem', 'Wales: Pembrokeshire/Sir Benfro'),
('gb', 'gb-pkn', 'Scotland: Kinross-shire'),
('gb', 'gb-pee', 'Scotland: Peeblesshire'),
('gb', 'gb-per', 'Scotland: Perthshire'),
('gb', 'gb-rad', 'Wales: Radnorshire/Sir Faesyfed'),
('gb', 'gb-rox', 'Scotland: Roxburghshire'),
('gb', 'gb-ros', 'Scotland: Ross-shire'),
('gb', 'gb-rfw', 'Scotland: Renfrewshire'),
('gb', 'gb-rut', 'England: Rutland'),
('gb', 'gb-say', 'England: South Yorkshire'),
('gb', 'gb-scb', 'Scottish Borders, The'),
('gb', 'gb-sfk', 'England: Suffolk'),
('gb', 'gb-shr', 'England: Shropshire'),
('gb', 'gb-slf', 'Scotland: Selkirkshire'),
('gb', 'gb-som', 'England: Somerset'),
('gb', 'gb-sos', 'Southend-on-Sea'),
('gb', 'gb-sry', 'England: Surrey'),
('gb', 'gb-sts', 'England: Staffordshire'),
('gb', 'gb-twh', 'N.Ireland: Tyrone'),
('gb', 'gb-vgl', 'Wales: Glamorgan/Morgannwg'),
('gb', 'gb-war', 'England: Warwickshire'),
('gb', 'gb-wbb', 'England: Berkshire'),
('gb', 'gb-wbw', 'England: Westmorland'),
('gb', 'gb-wby', 'England: West Yorkshire'),
('gb', 'gb-wil', 'England: Wiltshire'),
('gb', 'gb-wor', 'England: Worcestershire');




DELETE FROM `wp_country_province` WHERE `code_country` = 'ci';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('ci', 'ci-ab', 'Agneby'),
('ci', 'ci-ba', 'Bafing'),
('ci', 'ci-bs', 'Bas-Sassandra'),
('ci', 'ci-cm', 'Sud-Comoe'),
('ci', 'ci-dn', 'Denguele'),
('ci', 'ci-fr', 'Fromager'),
('ci', 'ci-lc', 'Lacs'),
('ci', 'ci-lg', 'Lagunes'),
('ci', 'ci-ma', 'Marahoue'),
('ci', 'ci-mg', 'Dix-Huit Montagnes'),
('ci', 'ci-my', 'Moyen-Cavally'),
('ci', 'ci-me', 'Moyen-Comoe'),
('ci', 'ci-zi', 'Nzi-Comoe'),
('ci', 'ci-nz', 'Haut-Sassandra'),
('ci', 'ci-su', 'Sud-Bandama'),
('ci', 'ci-sv', 'Savanes'),
('ci', 'ci-vb', 'Vallee du Bandama'),
('ci', 'ci-wo', 'Worodougou'),
('ci', 'ci-zz', 'Zanzan');



DELETE FROM `wp_country_province` WHERE `code_country` = 'za';
INSERT INTO `wp_country_province` (`code_country`, `code_province`, `province`) VALUES
('za', 'za-ec', 'Eastern Cape'),
('za', 'za-fs', 'Free State'),
('za', 'za-gt', 'Gauteng'),
('za', 'za-lp', 'Limpopo'),
('za', 'za-mp', 'Mpumalanga'),
('za', 'za-nc', 'Northern Cape'),
('za', 'za-nl', 'KwaZulu-Natal'),
('za', 'za-nw', 'North West'),
('za', 'za-wc', 'Western Cape');


   