SELECT 
    c.selector,
    c.date_created,
    YEAR (c.date_created) as year_created,
    CASE
        WHEN MONTH (c.date_created) = 1 THEN '01-January' 
        WHEN MONTH (c.date_created) = 2 THEN '02-February' 
        WHEN MONTH (c.date_created) = 3 THEN '03-March' 
        WHEN MONTH (c.date_created) = 4 THEN '04-April' 
        WHEN MONTH (c.date_created) = 5 THEN '05-May' 
        WHEN MONTH (c.date_created) = 6 THEN '06-June' 
        WHEN MONTH (c.date_created) = 7 THEN '07-July' 
        WHEN MONTH (c.date_created) = 8 THEN '08-August' 
        WHEN MONTH (c.date_created) = 9 THEN '09-September' 
        WHEN MONTH (c.date_created) = 10 THEN '10-October' 
        WHEN MONTH (c.date_created) = 11 THEN '11-November' 
        WHEN MONTH (c.date_created) = 12 THEN '12-December' 
    END as month_created,
    DAY (c.date_created ) as day_created,
    c.date_double_optin, 
    CASE 
        WHEN c.form = 6 THEN 'Sign_up' 
        WHEN c.form = 7 THEN 'Contact_us' 
    END as 'Form',
    c.email,
    c.firstname,
    c.lastname,
    c.country as country,
    CASE
        WHEN c.country = 'ad' THEN 'Andorra'
        WHEN c.country = 'ae' THEN 'United Arab Emirates'
        WHEN c.country = 'ag' THEN 'Antigua and Barbuda'
        WHEN c.country = 'ai' THEN 'Anguilla'
        WHEN c.country = 'al' THEN 'Albania'
        WHEN c.country = 'am' THEN 'Armenia'
        WHEN c.country = 'an' THEN 'Netherlands Antilles'
        WHEN c.country = 'ao' THEN 'Angola'
        WHEN c.country = 'ar' THEN 'Argentina'
        WHEN c.country = 'at' THEN 'Austria'
        WHEN c.country = 'au' THEN 'Australia'
        WHEN c.country = 'aw' THEN 'Aruba'
        WHEN c.country = 'az' THEN 'Azerbaijan'
        WHEN c.country = 'ba' THEN 'Bosnia and Herzegovina'
        WHEN c.country = 'bb' THEN 'Barbados'
        WHEN c.country = 'bd' THEN 'Bangladesh'
        WHEN c.country = 'be' THEN 'Belgium'
        WHEN c.country = 'bf' THEN 'Burkina Faso'
        WHEN c.country = 'bg' THEN 'Bulgaria'
        WHEN c.country = 'bh' THEN 'Bahrain'
        WHEN c.country = 'bi' THEN 'Burundi'
        WHEN c.country = 'bj' THEN 'Benin'
        WHEN c.country = 'bl' THEN 'Saint Barthelemy'
        WHEN c.country = 'bm' THEN 'Bermuda'
        WHEN c.country = 'bn' THEN 'Brunei'
        WHEN c.country = 'bo' THEN 'Bolivia'
        WHEN c.country = 'bq' THEN 'Caribbean Netherlands'
        WHEN c.country = 'br' THEN 'Brazil'
        WHEN c.country = 'bs' THEN 'Bahamas'
        WHEN c.country = 'bt' THEN 'Bhutan'
        WHEN c.country = 'bw' THEN 'Botswana'
        WHEN c.country = 'by' THEN 'Belarus'
        WHEN c.country = 'bz' THEN 'Belize'
        WHEN c.country = 'ca' THEN 'Canada'
        WHEN c.country = 'cd' THEN 'Congo Rép. Dém.'
        WHEN c.country = 'cf' THEN 'Central African Republic'
        WHEN c.country = 'cg' THEN 'Congo Brazzaville'
        WHEN c.country = 'ch' THEN 'Switzerland'
        WHEN c.country = 'ci' THEN 'Côte d''Ivoire'
        WHEN c.country = 'cl' THEN 'Chile'
        WHEN c.country = 'cm' THEN 'Cameroon'
        WHEN c.country = 'cn' THEN 'China'
        WHEN c.country = 'co' THEN 'Colombia'
        WHEN c.country = 'cr' THEN 'Costa Rica'
        WHEN c.country = 'cu' THEN 'Cuba'
        WHEN c.country = 'cv' THEN 'Cape Verde'
        WHEN c.country = 'cw' THEN 'Curaçao'
        WHEN c.country = 'cy' THEN 'Cyprus'
        WHEN c.country = 'cz' THEN 'Czech Republic'
        WHEN c.country = 'de' THEN 'Germany'
        WHEN c.country = 'dj' THEN 'Djibouti'
        WHEN c.country = 'dk' THEN 'Denmark'
        WHEN c.country = 'dm' THEN 'Dominica'
        WHEN c.country = 'do' THEN 'Dominican Republic'
        WHEN c.country = 'dz' THEN 'Algeria'
        WHEN c.country = 'ec' THEN 'Ecuador'
        WHEN c.country = 'ee' THEN 'Estonia'
        WHEN c.country = 'eg' THEN 'Egypt'
        WHEN c.country = 'eh' THEN 'West Sahara'
        WHEN c.country = 'er' THEN 'Eritrea'
        WHEN c.country = 'es' THEN 'Spain'
        WHEN c.country = 'et' THEN 'Ethiopia'
        WHEN c.country = 'fi' THEN 'Finland'
        WHEN c.country = 'fj' THEN 'Fiji'
        WHEN c.country = 'fk' THEN 'Falkland Islands'
        WHEN c.country = 'fm' THEN 'Micronesia'
        WHEN c.country = 'fr' THEN 'France'
        WHEN c.country = 'ga' THEN 'Gabon'
        WHEN c.country = 'gb' THEN 'United Kingdom'
        WHEN c.country = 'gd' THEN 'Grenada'
        WHEN c.country = 'ge' THEN 'Georgia'
        WHEN c.country = 'gf' THEN 'French Guiana'
        WHEN c.country = 'gh' THEN 'Ghana'
        WHEN c.country = 'gl' THEN 'Greenland'
        WHEN c.country = 'gm' THEN 'Gambia'
        WHEN c.country = 'gn' THEN 'Guinea'
        WHEN c.country = 'gp' THEN 'Guadeloupe'
        WHEN c.country = 'gq' THEN 'Equatorial Guinea'
        WHEN c.country = 'gr' THEN 'Greece'
        WHEN c.country = 'gt' THEN 'Guatemala'
        WHEN c.country = 'gu' THEN 'Guam'
        WHEN c.country = 'gw' THEN 'Guinea-Bissau'
        WHEN c.country = 'gy' THEN 'Guyana'
        WHEN c.country = 'hi' THEN 'Hawaii'
        WHEN c.country = 'hk' THEN 'Hong Kong'
        WHEN c.country = 'hn' THEN 'Honduras'
        WHEN c.country = 'hr' THEN 'Croatia'
        WHEN c.country = 'ht' THEN 'Haiti'
        WHEN c.country = 'hu' THEN 'Hungary'
        WHEN c.country = 'id' THEN 'Indonesia'
        WHEN c.country = 'ie' THEN 'Ireland'
        WHEN c.country = 'il' THEN 'Israel'
        WHEN c.country = 'in' THEN 'India'
        WHEN c.country = 'iq' THEN 'Iraq'
        WHEN c.country = 'ir' THEN 'Iran'
        WHEN c.country = 'is' THEN 'Iceland'
        WHEN c.country = 'it' THEN 'Italy'
        WHEN c.country = 'jm' THEN 'Jamaica'
        WHEN c.country = 'jo' THEN 'Jordan'
        WHEN c.country = 'jp' THEN 'Japan'
        WHEN c.country = 'ke' THEN 'Kenya'
        WHEN c.country = 'kg' THEN 'Kyrgyzstan'
        WHEN c.country = 'kh' THEN 'Cambodia'
        WHEN c.country = 'ki' THEN 'Kiribati'
        WHEN c.country = 'km' THEN 'Comoros'
        WHEN c.country = 'kn' THEN 'St. Kitts & Nevis'
        WHEN c.country = 'kp' THEN 'North Korea'
        WHEN c.country = 'kr' THEN 'South Korea'
        WHEN c.country = 'kw' THEN 'Kuwait'
        WHEN c.country = 'ky' THEN 'Cayman Islands'
        WHEN c.country = 'kz' THEN 'Kazakhstan'
        WHEN c.country = 'la' THEN 'Laos'
        WHEN c.country = 'lb' THEN 'Lebanon'
        WHEN c.country = 'lc' THEN 'St. Lucia'
        WHEN c.country = 'li' THEN 'Liechtenstein'
        WHEN c.country = 'lk' THEN 'Sri Lanka'
        WHEN c.country = 'lr' THEN 'Liberia'
        WHEN c.country = 'lt' THEN 'Lithuania'
        WHEN c.country = 'lu' THEN 'Luxembourg'
        WHEN c.country = 'lv' THEN 'Latvia'
        WHEN c.country = 'ly' THEN 'Libya'
        WHEN c.country = 'ma' THEN 'Morocco'
        WHEN c.country = 'mc' THEN 'Monaco'
        WHEN c.country = 'md' THEN 'Moldova'
        WHEN c.country = 'me' THEN 'Montenegro'
        WHEN c.country = 'mf' THEN 'Saint Martin'
        WHEN c.country = 'mg' THEN 'Madagascar'
        WHEN c.country = 'mh' THEN 'Marshall Islands'
        WHEN c.country = 'mk' THEN 'Macedonia'
        WHEN c.country = 'ml' THEN 'Mali'
        WHEN c.country = 'mm' THEN 'Myanmar'
        WHEN c.country = 'mn' THEN 'Mongolia'
        WHEN c.country = 'mq' THEN 'Martinique'
        WHEN c.country = 'mr' THEN 'Mauritania'
        WHEN c.country = 'ms' THEN 'Montserrat'
        WHEN c.country = 'mt' THEN 'Malta'
        WHEN c.country = 'mu' THEN 'Mauritius'
        WHEN c.country = 'mv' THEN 'Maldives'
        WHEN c.country = 'mw' THEN 'Malawi'
        WHEN c.country = 'mx' THEN 'Mexico'
        WHEN c.country = 'my' THEN 'Malaysia'
        WHEN c.country = 'mz' THEN 'Mozambique'
        WHEN c.country = 'na' THEN 'Namibia'
        WHEN c.country = 'nc' THEN 'New Caledonia'
        WHEN c.country = 'ne' THEN 'Niger'
        WHEN c.country = 'ng' THEN 'Nigeria'
        WHEN c.country = 'ni' THEN 'Nicaragua'
        WHEN c.country = 'nl' THEN 'Netherlands'
        WHEN c.country = 'no' THEN 'Norway'
        WHEN c.country = 'np' THEN 'Nepal'
        WHEN c.country = 'nr' THEN 'Nauru'
        WHEN c.country = 'nz' THEN 'New Zealand'
        WHEN c.country = 'om' THEN 'Oman'
        WHEN c.country = 'pa' THEN 'Panama'
        WHEN c.country = 'pe' THEN 'Peru'
        WHEN c.country = 'pf' THEN 'French Polynesia'
        WHEN c.country = 'pg' THEN 'Papua New Guinea'
        WHEN c.country = 'ph' THEN 'Philippines'
        WHEN c.country = 'pk' THEN 'Pakistan'
        WHEN c.country = 'pl' THEN 'Poland'
        WHEN c.country = 'pm' THEN 'Saint-Pierre et Miquelon'
        WHEN c.country = 'pr' THEN 'Puerto Rico'
        WHEN c.country = 'ps' THEN 'Palestine'
        WHEN c.country = 'pt' THEN 'Portugal'
        WHEN c.country = 'pw' THEN 'Palau'
        WHEN c.country = 'py' THEN 'Paraguay'
        WHEN c.country = 'qa' THEN 'Qatar'
        WHEN c.country = 're' THEN 'Reunion (Island)'
        WHEN c.country = 'ro' THEN 'Romania'
        WHEN c.country = 'rs' THEN 'Serbia'
        WHEN c.country = 'ru' THEN 'Russia'
        WHEN c.country = 'rw' THEN 'Rwanda'
        WHEN c.country = 'sa' THEN 'Saudi Arabia'
        WHEN c.country = 'sb' THEN 'Solomon Islands'
        WHEN c.country = 'sc' THEN 'Seychelles'
        WHEN c.country = 'sd' THEN 'Sudan'
        WHEN c.country = 'se' THEN 'Sweden'
        WHEN c.country = 'sg' THEN 'Singapore'
        WHEN c.country = 'sh' THEN 'Saint Helena'
        WHEN c.country = 'si' THEN 'Slovenia'
        WHEN c.country = 'sk' THEN 'Slovakia'
        WHEN c.country = 'sl' THEN 'Sierra Leone'
        WHEN c.country = 'sm' THEN 'San Marino'
        WHEN c.country = 'sn' THEN 'Senegal'
        WHEN c.country = 'so' THEN 'Somalia'
        WHEN c.country = 'sr' THEN 'Suriname'
        WHEN c.country = 'ss' THEN 'South Sudan'
        WHEN c.country = 'st' THEN 'Sao Tome and Principe'
        WHEN c.country = 'sv' THEN 'El Salvador'
        WHEN c.country = 'sx' THEN 'Sint Maarten'
        WHEN c.country = 'sy' THEN 'Syria'
        WHEN c.country = 'sz' THEN 'Swaziland'
        WHEN c.country = 'ku' THEN 'Kurdistan'
        WHEN c.country = 'tc' THEN 'Turks and Caicos Islands'
        WHEN c.country = 'td' THEN 'Tchad'
        WHEN c.country = 'tg' THEN 'Togo'
        WHEN c.country = 'th' THEN 'Thailand'
        WHEN c.country = 'tj' THEN 'Tajikistan'
        WHEN c.country = 'tk' THEN 'Tokelau'
        WHEN c.country = 'tl' THEN 'East Timor'
        WHEN c.country = 'tm' THEN 'Turkmenistan'
        WHEN c.country = 'tn' THEN 'Tunisia'
        WHEN c.country = 'to' THEN 'Tonga'
        WHEN c.country = 'tr' THEN 'Turkey'
        WHEN c.country = 'tt' THEN 'Trinidad and Tobago'
        WHEN c.country = 'tv' THEN 'Tuvalu'
        WHEN c.country = 'tw' THEN 'Taiwan'
        WHEN c.country = 'tz' THEN 'Tanzania'
        WHEN c.country = 'ua' THEN 'Ukraine'
        WHEN c.country = 'ug' THEN 'Uganda'
        WHEN c.country = 'um' THEN 'US Minor Outlying Islands'
        WHEN c.country = 'us' THEN 'United States'
        WHEN c.country = 'uy' THEN 'Uruguay'
        WHEN c.country = 'uz' THEN 'Uzbekistan'
        WHEN c.country = 'vc' THEN 'St. Vincent & the Grenadines'
        WHEN c.country = 've' THEN 'Venezuela'
        WHEN c.country = 'vg' THEN 'British Virgin Islands'
        WHEN c.country = 'vi' THEN 'Virgin Islands, U.S.'
        WHEN c.country = 'vn' THEN 'Vietnam'
        WHEN c.country = 'vu' THEN 'Vanatu'
        WHEN c.country = 'wf' THEN 'Wallis and Futuna Islands'
        WHEN c.country = 'ws' THEN 'Samoa'
        WHEN c.country = 'xz' THEN 'Tibet'
        WHEN c.country = 'ye' THEN 'Yemen'
        WHEN c.country = 'yt' THEN 'Mayotte'
        WHEN c.country = 'za' THEN 'South Africa'
        WHEN c.country = 'zm' THEN 'Zambia'
        WHEN c.country = 'zw' THEN 'Zimbabwe'
        ELSE 'Unknow'
    END as 'country',
    c.language as language,
    CASE 
        WHEN c.language = 'ar' THEN 'Arabic'
        WHEN c.language = 'az' THEN 'Azerbaijani'
        WHEN c.language = 'be' THEN 'Belarusian'
        WHEN c.language = 'bg' THEN 'Bulgarian'
        WHEN c.language = 'bn' THEN 'Bengali'
        WHEN c.language = 'bs' THEN 'Bosnian'
        WHEN c.language = 'cn' THEN 'Chinese'
        WHEN c.language = 'cs' THEN 'Czech'
        WHEN c.language = 'da' THEN 'Danish'
        WHEN c.language = 'de' THEN 'German'
        WHEN c.language = 'el' THEN 'Greek'
        WHEN c.language = 'en' THEN 'English'
        WHEN c.language = 'es' THEN 'Spanish'
        WHEN c.language = 'et' THEN 'Estonian'
        WHEN c.language = 'fa' THEN 'Persian'
        WHEN c.language = 'fi' THEN 'Finnish'
        WHEN c.language = 'fr' THEN 'French'
        WHEN c.language = 'he' THEN 'Hebrew'
        WHEN c.language = 'hi' THEN 'Hindi'
        WHEN c.language = 'hr' THEN 'Croatian'
        WHEN c.language = 'hu' THEN 'Hungarian'
        WHEN c.language = 'hy' THEN 'Armenian'
        WHEN c.language = 'id' THEN 'Indonesian'
        WHEN c.language = 'it' THEN 'Italian'
        WHEN c.language = 'ja' THEN 'Japanese'
        WHEN c.language = 'km' THEN 'Khmer'
        WHEN c.language = 'ko' THEN 'Korean'
        WHEN c.language = 'lt' THEN 'Lithuanian'
        WHEN c.language = 'mn' THEN 'Mongolian'
        WHEN c.language = 'ne' THEN 'Nepali'
        WHEN c.language = 'nl' THEN 'Dutch'
        WHEN c.language = 'no' THEN 'Norwegian'
        WHEN c.language = 'pl' THEN 'Polish'
        WHEN c.language = 'pt' THEN 'Portuguese'
        WHEN c.language = 'ro' THEN 'Romanian'
        WHEN c.language = 'ru' THEN 'Russian'
        WHEN c.language = 'si' THEN 'Sinhalese'
        WHEN c.language = 'sk' THEN 'Slovak'
        WHEN c.language = 'sl' THEN 'Slovenian'
        WHEN c.language = 'sr' THEN 'Serbian'
        WHEN c.language = 'sv' THEN 'Swedish'
        WHEN c.language = 'th' THEN 'Thai'
        WHEN c.language = 'tl' THEN 'Tagalog'
        WHEN c.language = 'tr' THEN 'Turkish'
        WHEN c.language = 'tw' THEN 'Twi'
        WHEN c.language = 'uk' THEN 'Ukrainian'
        WHEN c.language = 'vi' THEN 'Viêt Namese'
        WHEN c.language = 'zh' THEN 'Chinese'
        ELSE 'Unknow'
    END as 'language',
    c.area,
    CASE 
        WHEN c.date_double_optin IS NOT NULL THEN 'Yes'
        ELSE 'No'
    END as double_optin,
    CASE 
        WHEN c.news_event <> '' THEN 'Yes'
        WHEN c.form = 6 THEN 'Yes'
        ELSE 'No'
    END as news_event,
    CASE 
        WHEN cs.email is not NULL THEN 1
        ELSE 0
    END as 'spam_count',
    c.message
FROM wp_contacts c
LEFT JOIN wp_contacts_spam cs 
  on cs.email = c.email
ORDER BY c.date_created
